INSERT INTO Miasto VALUES(1,'Krakow');
INSERT INTO Miasto VALUES(2,'Poznan');
INSERT INTO Miasto VALUES(3,'Szczecin');
INSERT INTO Miasto VALUES(4,'Gdansk');
INSERT INTO Miasto VALUES(5,'Kielce');
INSERT INTO Miasto VALUES(6,'Warszawa');
INSERT INTO Miasto VALUES(7,'Elblag');
INSERT INTO Miasto VALUES(8,'Torun');
INSERT INTO Miasto VALUES(9,'Rzeszow');
